builder:
  track: dev

labels:
  app-group: estafette-ci-extensions
  team: estafette-team
  language: golang

version:
  semver:
    major: 0
    minor: 1

stages:
  build:
    image: golang:1.15.6-alpine3.12
    env:
      CGO_ENABLED: 0
      GOOS: linux
    commands:
    - go test ./...
    - go build -a -installsuffix cgo -ldflags "-X main.appgroup=${ESTAFETTE_LABEL_APP_GROUP} -X main.app=${ESTAFETTE_GIT_NAME} -X main.version=${ESTAFETTE_BUILD_VERSION} -X main.revision=${ESTAFETTE_GIT_REVISION} -X main.branch=${ESTAFETTE_GIT_BRANCH} -X main.buildDate=${ESTAFETTE_BUILD_DATETIME}" -o ./publish/${ESTAFETTE_GIT_NAME} .

  bake:
    image: extensions/docker:stable
    action: build
    container: docker
    inline: |
      FROM alpine:3.12

      ARG DIVE_VERSION=0.9.2

      RUN wget -O- https://github.com/wagoodman/dive/releases/download/v${DIVE_VERSION}/dive_${DIVE_VERSION}_linux_amd64.tar.gz | \
          tar -xzf - -C / \
          && /dive version

      ARG TRIVY_VERSION=0.15.0

      RUN wget -O- https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz | \
          tar -xzf - -C / \
          && /trivy --version \
          && /trivy --cache-dir /trivy-cache image --light --no-progress --download-db-only \
          && /trivy --cache-dir /trivy-cache image --severity CRITICAL --light --skip-update --no-progress --ignore-unfixed alpine:3.11

      FROM scratch

      LABEL maintainer="estafette.io"

      COPY ${ESTAFETTE_GIT_NAME} /
      COPY ca-certificates.crt /etc/ssl/certs/
      COPY --from=0 /dive /dive
      COPY --from=0 /trivy /trivy
      COPY --from=0 /trivy-cache /trivy-cache
      COPY --from=0 /tmp /tmp

      ENV PATH="/dod:$PATH" \
          ESTAFETTE_LOG_FORMAT="console"

      ENTRYPOINT ["/${ESTAFETTE_GIT_NAME}"]
    repositories:
    - extensions
    path: ./publish
    dontExpand:
    - DIVE_VERSION
    - TRIVY_VERSION
    copy:
    - /etc/ssl/certs/ca-certificates.crt

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:stable
        action: dive
        container: docker
        repositories:
        - extensions

      vulnerability-scan:
        image: extensions/docker:stable
        action: trivy
        container: docker
        repositories:
        - extensions

  tests:
    parallelStages:
      test-build:
        image: extensions/docker:${ESTAFETTE_BUILD_VERSION}
        action: build
        container: docker-test
        inline: |
          FROM docker:19.03.13

          LABEL maintainer="estafette.io"

          COPY ${ESTAFETTE_GIT_NAME} /
          COPY ca-certificates.crt /etc/ssl/certs/

          ENTRYPOINT ["/${ESTAFETTE_GIT_NAME}"]
        repositories:
        - extensions
        path: ./publish
        copy:
        - /etc/ssl/certs/ca-certificates.crt

      test-build-from-private-registry:
        image: extensions/docker:${ESTAFETTE_BUILD_VERSION}
        action: build
        no-cache: true
        container: hugo-test
        inline: |
          FROM estafette/hugo:0.62.2

          COPY ca-certificates.crt /etc/ssl/certs/
          COPY publish /publish
        repositories:
        - extensions
        path: ./publish-hugo
        copy:
        - /etc/ssl/certs/ca-certificates.crt
        - publish

      test-dive:
        image: extensions/docker:${ESTAFETTE_BUILD_VERSION}
        action: dive
        container: docker
        repositories:
        - extensions

      test-trivy:
        image: extensions/docker:${ESTAFETTE_BUILD_VERSION}
        action: trivy
        container: docker
        repositories:
        - extensions

  push-to-docker-hub:
    image: extensions/docker:stable
    action: push
    container: docker
    repositories:
    - extensions

  slack-notify:
    image: extensions/slack-build-status:dev
    workspace: estafette
    channels:
    - '#build-status'
    when:
      status == 'succeeded' ||
      status == 'failed'

releases:
  windows:
    builder:
      os: windows
    clone: true
    stages:
      build:
        image: estafette/golang:1.15.6-windowsservercore-ltsc2019
        env:
          CGO_ENABLED: 0
          GOOS: windows
          GOARCH: amd64
        commands:
        - go build -v -ldflags "-X main.app=$env:ESTAFETTE_GIT_NAME -X main.version=$env:ESTAFETTE_BUILD_VERSION -X main.revision=$env:ESTAFETTE_GIT_REVISION -X main.branch=$env:ESTAFETTE_GIT_BRANCH -X main.buildDate=$env:ESTAFETTE_BUILD_DATETIME" -o ./publish/$env:ESTAFETTE_GIT_NAME.exe

      bake:
        image: extensions/docker:windowsservercore-ltsc2019
        action: build
        no-cache: true
        expand-variables: false
        container: docker
        repositories:
        - extensions
        dockerfile: Dockerfile.windowsservercore-ltsc2019
        path: ./publish

      test:
        image: extensions/docker:${ESTAFETTE_BUILD_VERSION}
        action: build
        container: docker-test
        versionTagSuffix: -suffix
        inline: |
          FROM mcr.microsoft.com/windows/servercore:ltsc2019

          RUN netsh interface ipv4 show interfaces
        repositories:
        - extensions

      push-to-docker-hub:
        image: extensions/docker:windowsservercore-ltsc2019
        action: push
        container: docker
        repositories:
        - extensions
        tags:
        - windowsservercore-ltsc2019
        pushVersionTag: false

  dev:
    triggers:
    - pipeline:
        name: self
        branch: .+
    stages:
      tag-container-image:
        image: extensions/docker:stable
        action: tag
        container: docker
        repositories:
        - extensions
        tags:
        - dev

  beta:
    stages:
      tag-container-image:
        image: extensions/docker:stable
        action: tag
        container: docker
        repositories:
        - extensions
        tags:
        - beta

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'

  stable:
    stages:
      tag-container-image:
        image: extensions/docker:stable
        action: tag
        container: docker
        repositories:
        - extensions
        tags:
        - stable
        - latest

      slack-notify:
        image: extensions/slack-build-status:dev
        workspace: estafette
        channels:
        - '#build-status'
        when:
          status == 'succeeded' ||
          status == 'failed'